apiVersion: v1
kind: Service
metadata:
  name: acme-challange-service
spec:
  ports:
  - port: 80
    targetPort: 8089
  selector:
    acme.cert-manager.io/http01-solver: "true"

---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: acme-challange-mapping
spec:
  hostname: playeconomy1384.northeurope.cloudapp.azure.com
  prefix: /.well-known/acme-challenge/
  rewrite: ""
  service: acme-challange-service
