# identity
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: identity-mapping
spec:
  hostname: playeconomy1384.northeurope.cloudapp.azure.com
  prefix: /identity-svc/
  service: identity-service.identity

--- 
# catalog
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: catalog-mapping
spec:
  hostname: playeconomy1384.northeurope.cloudapp.azure.com
  prefix: /catalog-svc/
  service: catalog-service.catalog

--- 
# inventory
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: inventory-mapping
spec:
  hostname: playeconomy1384.northeurope.cloudapp.azure.com
  prefix: /inventory-svc/
  service: inventory-service.inventory

--- 
# trading
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: trading-mapping
spec:
  hostname: playeconomy1384.northeurope.cloudapp.azure.com
  prefix: /trading-svc/
  service: trading-service.trading

---
# frontend
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: frontend-mapping
spec:
  hostname: playeconomy1384.northeurope.cloudapp.azure.com
  prefix: /
  service: frontend-client.frontend

---
# seq mapping
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: seq-mapping
spec:
  hostname: playeconomy1384.northeurope.cloudapp.azure.com
  prefix: /seq/
  service: seq.observability
  
---
# jaeger mapping
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: jaeger-mapping
spec:
  hostname: playeconomy1384.northeurope.cloudapp.azure.com
  prefix: /jaeger/
  rewrite: ""
  service: jaeger-query.observability:16686

---
# prometheus mapping
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: prometheus-mapping
spec:
  hostname: playeconomy1384.northeurope.cloudapp.azure.com
  prefix: /prometheus/
  service: prometheus-operated.observability:9090

---
# seq mapping
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: grafana-mapping
spec:
  hostname: playeconomy1384.northeurope.cloudapp.azure.com
  prefix: /grafana/
  service: prometheus-grafana.observability:80