apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: playeconomy1384-tls-cert
spec:
  secretName: playeconomy1384-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "playeconomy1384.northeurope.cloudapp.azure.com"