apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.microserviceName }}-serviceaccount"
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.clientId }}
  labels:
    azure.workload.identity/use: "true"