envVariables:
  ServiceSettings__MessageBroker: SERVICEBUS
  ServiceSettings__KeyVaultName: playeconomy1384

resources:
  limits:
    memory: "128Mi"
    cpu: "200m"

container:
  liveness:
    path: /health/live
    initialDelaySeconds: 10
  readyness: 
    path: /health/ready
    initialDelaySeconds: 10

service:
  type: ClusterIP
  port: 80
