provisionDataStore:
  cassandra: false
allInOne:
  enabled: true
  extraEnv:
    - name: QUERY_BASE_PATH
      value: /jaeger/
  ingress:
    enabled: false
storage:
  type: none
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false