version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - pe-mongodbdata:/data/db
    networks:
      - pe-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - pe-rabbitmqdata:/var/lib/rabbitmq
    networks:
      - pe-network
    hostname: rabbitmq

volumes:
  pe-mongodbdata:
  pe-rabbitmqdata:

networks:
  pe-network:
    name: pe-network
    driver: bridge
